//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_5_CRUD_with_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public int RadnikID { get; set; }
        public string Ime { get; set; }
        public Nullable<int> Godine { get; set; }
        public string Sektor { get; set; }
        public string Grad { get; set; }
    }
}
